### PR TITLE
Fix of bug causing  wrong goto position if goal in the upper part of …

### PR DESCRIPTION
**Pull request by EnockNitti**
…canavas

### CODE REVIEW

**Comment by fire-eggs** [comment]
Many thanks!

**Comment by EnockNitti** [comment]
Hi !

Have another matter to discuss.
The handling of "cargo" on carriers is different from other sea-units.
I found this when I was checking on how the max load on carriers was taken
care of.
I don't understand the purpose of this difference. Do you have any opinions
on this ?
There are some  bugs here: A bomber flying over a full carrier is losing
its movement points. It should not.
If a carrier with more than 8 sentried(spelling?) units are moving, the
extra units just stay in place still  sentried.
My problem is: should I just patch it up, or should I rewrite it to a code
more like other sea units ?

(Side note: And I think that sea units should not lose their move points
when entering a city.
Frustrating when a city is just used as canal).

And about End-of-line hell........
I think the comparing of file changes in git is very primitive.
I am missing the option to reduce all sequences of blanks to one blank
 before comparison.
This would solve all problems with eol, space/tab and extra spaces at end
of text.
Anyway: how do you want eol should be handled in this project ?

Side note2: I have spent more time with CIV1 than all other computer games
together, and I am
still running it now and then. So I am quite familiar with its
idiosyncrasies   :)

**Comment by fire-eggs** [comment]
Hi Enock!
> So I am quite familiar with its idiosyncrasies 
I always play as absolute despotic conqueror so I never reach more advanced technologies such as carriers. Having more users who know about Civ1's "advanced" idiosyncrasies, the better!

RE: carriers
I added a new issue. I'm not familiar with the "cargo" code, so can't provide much useful feedback. My approach is usually to patch it up first, then refactor to get "commonality". Any improvements you make in this area will be appreciated!

RE: ports
Agreed. I'm pretty sure this was changed for Civ2(?) and onwards. I'd have no problem with making this change as long as it's behind "cheat" control. Added an issue.

> Anyway: how do you want eol should be handled in this project ?

You might discuss / coordinate with @iegik - he has proposed(?) some github control over this. And obviously, the pull request from @Andersw88. I'm most concerned about consistency - I don't want to struggle with huge diffs which are only whitespace.

Speaking of consistency, thank you for fixing the brackets in your checkin to 'goto.cs'! I'm ashamed to have missed that from @iegik's pull request ...

I've activated Discussions for the repository, and will add the "eol" topic shortly.

I'll be honest and say I'm more motivated when there is more activity from other folks. Kind of difficult to keep going when it seems like "only me". Many thanks for the ideas and questions!
Kevin

**Comment by EnockNitti** [comment]
Hi !
 I have two modes of play "despotic conqueror" or "max science before 0AD
using big city". Always as Emperor.

It was a long time since I was actually was using any carriers. Why I
bother is because of my work with "smart goto".
I have some saved games with carriers I am using for testing.
And my work with "smart goto" was from my frustration of units "derailing"
and ships going astray.
Maybe I will do some more tuning of goto. Now the code is a bit of a
compromise due to the fact
that movement costs varies for land units (sometimes in a strange way), but
not for sea/air units.

I am new to C# and Git. I think this is a fun project to use to learn.

About eol: I can use any method, as long it is consistent. Once I worked a
system using CR. Later
in a mixed unix-windows environment.
You decide what to do. And perhaps decide about using space or tab for
indention.

OK: I take a further look at the carrier code.

**Pull request merged**
